import {
  Briefcase,
  Laptop,
  Building2,
  TrendingUp,
  TrendingDown,
  Gift,
  CirclePlus,
  Home,
  Lightbulb,
  Wifi,
  Wrench,
  Receipt,
  HeartPulse,
  Car,
  ShieldCheck,
  HeartHandshake,
  ShoppingCart,
  UtensilsCrossed,
  Bike,
  Coffee,
  Fuel,
  Bus,
  CarTaxiFront,
  Cog,
  ParkingCircle,
  Stethoscope,
  Pill,
  Dumbbell,
  Brain,
  SprayCan,
  Shirt,
  Scissors,
  PawPrint,
  Clapperboard,
  Repeat,
  Palette,
  Plane,
  PartyPopper,
  Baby,
  GraduationCap,
  BookOpen,
  Backpack,
  CreditCard,
  WalletCards,
  Landmark,
  LifeBuoy,
  Palmtree,
  BarChart3,
  Sofa,
  Luggage,
  Banknote,
  Calculator,
  HandHeart,
  CircleHelp,
  ShoppingBag,
  PiggyBank,
  Wallet,
  Tag,
  Smartphone,
  SplitSquareHorizontal,
  MoreHorizontal,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP = {
  briefcase: Briefcase,
  laptop: Laptop,
  building: Building2,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  gift: Gift,
  'circle-plus': CirclePlus,
  home: Home,
  lightbulb: Lightbulb,
  wifi: Wifi,
  wrench: Wrench,
  receipt: Receipt,
  'heart-pulse': HeartPulse,
  car: Car,
  'shield-check': ShieldCheck,
  'heart-handshake': HeartHandshake,
  'shopping-cart': ShoppingCart,
  utensils: UtensilsCrossed,
  bike: Bike,
  coffee: Coffee,
  fuel: Fuel,
  bus: Bus,
  taxi: CarTaxiFront,
  cog: Cog,
  parking: ParkingCircle,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  brain: Brain,
  spray: SprayCan,
  shirt: Shirt,
  scissors: Scissors,
  paw: PawPrint,
  clapperboard: Clapperboard,
  repeat: Repeat,
  palette: Palette,
  plane: Plane,
  party: PartyPopper,
  baby: Baby,
  'graduation-cap': GraduationCap,
  book: BookOpen,
  backpack: Backpack,
  'credit-card': CreditCard,
  'wallet-cards': WalletCards,
  landmark: Landmark,
  'life-buoy': LifeBuoy,
  palmtree: Palmtree,
  'bar-chart': BarChart3,
  sofa: Sofa,
  luggage: Luggage,
  banknote: Banknote,
  calculator: Calculator,
  'hand-heart': HandHeart,
  'help-circle': CircleHelp,
  'shopping-bag': ShoppingBag,
  'piggy-bank': PiggyBank,
  wallet: Wallet,
  tag: Tag,
  smartphone: Smartphone,
  split: SplitSquareHorizontal,
  more: MoreHorizontal,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICON_MAP;

export const ICON_KEYS = Object.keys(ICON_MAP) as IconKey[];

export const DEFAULT_ICON_KEY: IconKey = 'tag';

export function resolveIcon(key: string | undefined): LucideIcon {
  return ICON_MAP[key as IconKey] ?? ICON_MAP[DEFAULT_ICON_KEY];
}
