export const SEED_NAME_RU: Record<string, string> = {
  Income: 'Доходы',
  'Bills & Housing': 'Счета и жильё',
  Insurance: 'Страхование',
  Food: 'Еда',
  Transport: 'Транспорт',
  Health: 'Здоровье',
  Personal: 'Личное',
  Lifestyle: 'Образ жизни',
  'Family & Education': 'Семья и образование',
  'Debt Payments': 'Платежи по долгам',
  'Savings & Goals': 'Накопления и цели',
  Other: 'Другое',
  Housing: 'Жильё',
  'Savings & Debt': 'Накопления и долги',

  Salary: 'Зарплата',
  'Freelance / Side income': 'Фриланс / доп. доход',
  'Business income': 'Доход от бизнеса',
  'Investment income': 'Инвестиционный доход',
  'Gifts & Refunds': 'Подарки и возвраты',
  'Other income': 'Другой доход',
  'Rent / Mortgage': 'Аренда / ипотека',
  Utilities: 'Коммунальные услуги',
  'Internet & Mobile': 'Интернет и связь',
  'Home maintenance': 'Ремонт и обслуживание жилья',
  'Property tax': 'Налог на имущество',
  Auto: 'Авто',
  'Home / Renters': 'Жильё / аренда (страхование)',
  Life: 'Жизнь',
  Groceries: 'Продукты',
  'Restaurants & Cafes': 'Кафе и рестораны',
  Delivery: 'Доставка еды',
  Coffee: 'Кофе',
  Fuel: 'Топливо',
  'Public transport': 'Общественный транспорт',
  'Taxi / Ride-share': 'Такси',
  'Car maintenance': 'Обслуживание авто',
  'Parking & Tolls': 'Парковка и платные дороги',
  'Doctor & Dentist': 'Врач и стоматолог',
  Pharmacy: 'Аптека',
  'Fitness & Sport': 'Фитнес и спорт',
  Therapy: 'Терапия',
  'Household supplies': 'Бытовые товары',
  'Clothing & Shoes': 'Одежда и обувь',
  'Beauty & Haircut': 'Красота и стрижка',
  Pets: 'Питомцы',
  Entertainment: 'Развлечения',
  Subscriptions: 'Подписки',
  Hobbies: 'Хобби',
  'Travel & Vacation': 'Путешествия',
  'Gifts & Celebrations': 'Подарки и праздники',
  Childcare: 'Уход за детьми',
  'School / Tuition': 'Школа / обучение',
  'Courses & Books': 'Курсы и книги',
  "Kids' expenses": 'Расходы на детей',
  'Credit card payment': 'Платёж по кредитке',
  'Loan payment': 'Платёж по кредиту',
  'Interest & Fees': 'Проценты и комиссии',
  'Emergency Fund': 'Финансовая подушка',
  Retirement: 'Пенсионные накопления',
  Investments: 'Инвестиции',
  'Big purchase': 'Крупная покупка',
  'Vacation fund': 'Накопления на отпуск',
  'Bank fees': 'Банковские комиссии',
  Taxes: 'Налоги',
  Charity: 'Благотворительность',
  Uncategorized: 'Без категории',
  Shopping: 'Покупки',
  Savings: 'Накопления',
};
